### ISSUE TITLE
:source and :through knowledge

### ISSUE THREAD

**Issue by rsfarzo** [appdev-lessons/refactoring-msm-gui-2#1]
Students aren't finding info for `:source`  and `:through` association attributes.   

A subsequent assignment, Photogram Associations,  has tips in the source code model comments, and a link to the Ruby Guides.

I think we need an example in the notes and a link to https://guides.rubyonrails.org/association_basics.html#options-for-has-many-source

**Comment by bpurinton** [comment]
Thanks for opening the issue! I've added a new lesson section:

https://learn.firstdraft.com/lessons/156-refactoring-msm-gui-2#the-source-and-through-keywords

If it looks good, I'll also add a link back to that section in the Photogram Associations lesson.

**Comment by heratyian** [comment]
> Thanks for opening the issue! I've added a new lesson section:
> 
> https://learn.firstdraft.com/lessons/156-refactoring-msm-gui-2#the-source-and-through-keywords
> 
> If it looks good, I'll also add a link back to that section in the Photogram Associations lesson.

I like this. Very clear example.
